### ISSUE TITLE
Add support for remote access via iPad

### ISSUE THREAD

**Issue by AlexanderWillner** [AlexanderWillner/KanbanView#13]
**Goal**
- As a user
- I want to access KanbanView on the iPad
- so that I'm more mobile

**Suggested approach**
In order to achieve this goal I suggest to enhance the documentation in order to explain how to do this.

**Additional context**
 - [x] Add configuration to listen on port 0.0.0.0
 - [x] Add link to copy public URL
 - [x] Add icon for saving the page as a web app
 - [x] Test layout on iPadOS
 - [x] Fix layout on iPadOS (e.g. replace input selector)

**Comment by lucbeaulieu** [comment]
This would indeed be a great extension!

**Comment by AlexanderWillner** [comment]
Preview:
<img width="1109" alt="Screen Shot 2020-04-23 at 14 34 19" src="https://user-images.githubusercontent.com/307605/80100116-c3bc8f00-856f-11ea-82c3-df79bf12da5d.png">

<img width="1109" alt="Screen Shot 2020-04-23 at 14 33 23" src="https://user-images.githubusercontent.com/307605/80100070-b7d0cd00-856f-11ea-8b62-23913e81fbc1.png">

**Comment by AlexanderWillner** [comment]
<img width="1110" alt="Screen Shot 2020-05-01 at 14 59 08" src="https://user-images.githubusercontent.com/307605/80808087-0b21cb80-8bbf-11ea-8961-18e90c53f182.png">
<img width="1110" alt="Screen Shot 2020-05-01 at 14 59 39" src="https://user-images.githubusercontent.com/307605/80808096-107f1600-8bbf-11ea-975b-fbc28fcb5045.png">
