### ISSUE TITLE
Eisenhower matrix: tag configuration

### ISSUE THREAD

**Issue by lucbeaulieu** [AlexanderWillner/KanbanView#20]
What are the settings to get tasks/projects in the Eisenhower matrix in version 2.6.0?

**Comment by AlexanderWillner** [comment]
Tasks that are in Today and marked with tags A, B, C and D

**Comment by lucbeaulieu** [comment]
Ah. Any chance that these tags could be associated/changed in the pref also?

**Comment by AlexanderWillner** [comment]
Why not. Out of interest: which tags would you use?

**Comment by lucbeaulieu** [comment]
Priority tags!
