### ISSUE TITLE
MIT column does not show tasks with user defined tag

### ISSUE THREAD

**Issue by nilsberg** [AlexanderWillner/KanbanView#21]
**To Reproduce**
1. In `~/.kanbanviewrc` set `tag_mit` to something else than `MIT`, e.g. `Wichtig`.
2. Start or restart Kanbanview.

**Expected behavior**
Tasks with the user defined tag appear in the 'MIT' column.
(However they don't, and tasks tagged with `MIT` still appear in it.)

**Additional context**
Clicking the 'MIT' column opens the correct tag in Things and the tooltip of the column shows the user defined tag. So reading `tag_mit` from the config file seems successful.

**Comment by AlexanderWillner** [comment]
Thanks for the feedback! Please test the update. Should be fixed.

**Comment by nilsberg** [comment]
The tasks show up, however there are now duplicated columns.

**Comment by nilsberg** [comment]
Thank you!
