### ISSUE TITLE
ModuleNotFoundError: No module named 'things'

### ISSUE THREAD

**Issue by alapolloni** [AlexanderWillner/KanbanView#29]
Hi, I'm running a clean version of python3.9  installed via brew.

after make install, etc and running *things-kanban* or *things-api* I get:

>   File "/usr/local/lib/python3.9/site-packages/things3_api-2.7.0.dev1-py3.9.egg/things3/things3.py", line 18, in <module>
> ModuleNotFoundError: No module named 'things'

this, in things3.py, gives me pause

```
 # the new core library, migration ongoing
 import things
```

I ran a find and I'm not seeing a things.py

**Comment by AlexanderWillner** [comment]
It's a new library that should get installed via `make deps-install` or your can run `pip3 install things.py`.

**Comment by alapolloni** [comment]
the `pip3 install things.py` did it for me. thanks!
