### ISSUE TITLE
Extracting (not-completed/not trashed) number of tasks for each project

### ISSUE THREAD

**Issue by lucbeaulieu** [AlexanderWillner/KanbanView#6]
In the following:
SELECT
	PROJECT.title,
	(SELECT COUNT(uuid) FROM TMTask WHERE project = PROJECT.uuid)
FROM
	TMTask as PROJECT
WHERE
	PROJECT.type = 1

This extract all tasks even completed ones. Adding more conditions (I tried in both WHERE statements) does not seems to change the count #. 

In addition, it would be nice to keep information about the area title (for filtering) so that project level display in the KanbanView is possible.

**Comment by AlexanderWillner** [comment]
As this is partly implemented in the code now, this is how it's currently counting tasks in projects:

```
 SELECT DISTINCT
                TASK.uuid,
                TASK.title,
				(SELECT COUNT(uuid)
                 FROM TMTask
                 WHERE
                   project = TASK.uuid AND
                   trashed = 0 AND
                   status = 0
                ),
                AREA.title AS area
            FROM
                TMTask AS TASK
            LEFT OUTER JOIN
                TMArea AREA ON TASK.area = AREA.uuid
            WHERE                
            TASK.trashed = 0 AND
            TASK.status = 0 AND
            TASK.type = 1
```

**Comment by AlexanderWillner** [comment]
by the way: I just added an experimental toggle to work on projects, instead of tasks...

**Comment by lucbeaulieu** [comment]
My approach to counting was not right and yours work perfectly. I am proposing the following change to the main sql query that will return a 9th term, I_COUNT. From there, the number of tasks within a project could probably by (easily) introduced in the CSS style for display when the main box is filled with a project rather than a task (in addition to any due date of course).

sql = """
            SELECT DISTINCT
                TASK.uuid,
                TASK.title,
                CASE
                    WHEN AREA.title IS NOT NULL THEN AREA.title
                    WHEN PROJECT.title IS NOT NULL THEN PROJECT.title
                    WHEN HEADING.title IS NOT NULL THEN HEADING.title
                END,
                CASE
                    WHEN AREA.uuid IS NOT NULL THEN AREA.uuid
                    WHEN PROJECT.uuid IS NOT NULL THEN PROJECT.uuid
                END,
                CASE
                    WHEN TASK.recurrenceRule IS NULL
                    THEN date(TASK.dueDate,"unixepoch")
                ELSE NULL
                END,
                date(TASK.creationDate,"unixepoch"),
                date(TASK.userModificationDate,"unixepoch"),
                date(TASK.startDate,"unixepoch"),
                date(TASK.stopDate,"unixepoch"),
                (SELECT COUNT(uuid)
                    FROM TMTask
                    WHERE
                        project = TASK.uuid AND
                        trashed = 0 AND
                        status = 0
                ) AS NBT
            FROM
                TMTask AS TASK
            LEFT OUTER JOIN
                TMTask PROJECT ON TASK.project = PROJECT.uuid
            LEFT OUTER JOIN
                TMArea AREA ON TASK.area = AREA.uuid
            LEFT OUTER JOIN
                TMTask HEADING ON TASK.actionGroup = HEADING.uuid
            LEFT OUTER JOIN
                TMTask HEADPROJ ON HEADING.project = HEADPROJ.uuid
            LEFT OUTER JOIN
                TMTaskTag TAGS ON TASK.uuid = TAGS.tasks
            LEFT OUTER JOIN
                TMTag TAG ON TAGS.tags = TAG.uuid
            WHERE
                """ + sql

Here are two project level KanbanView:

  def get_empty_projects(self):
        """Get projects that are empty"""
        query = f"""
            TASK.{self.IS_NOT_TRASHED} AND
            TASK.{self.IS_OPEN} AND
            TASK.{self.IS_PROJECT} AND
            NBT = 0
            GROUP BY TASK.uuid
            """
        return self.get_rows(query)

    def get_someday_projects(self):
        """Get someday projects."""
        query = f"""
            TASK.{self.IS_NOT_TRASHED} AND
            TASK.{self.IS_OPEN} AND
            TASK.{self.IS_PROJECT} AND
            TASK.{self.IS_SOMEDAY}
            GROUP BY TASK.uuid
            """
        return self.get_rows(query)

**Comment by lucbeaulieu** [comment]
Made things a bit nicer code wise:
  def get_ment_projects(self):
        """Get projects. from the specific Area - Mentoring"""
        query = f"""
            TASK.{self.IS_NOT_TRASHED} AND
            TASK.{self.IS_OPEN} AND
            TASK.{self.IS_PROJECT} AND
            Area.{self.IS_MENTORING}
		    ORDER BY TASK.duedate
            """
        return self.get_rows(query)

with:
    IS_MENTORING ="title IS 'Mentoring'"

This one is to have an overview of all my undergrad and grad students, as well as postdocs and research assistants along with their expected graduation/end date.

I made similar ones for all my active research grants/projects as well as my active writing projects (like grant writing!), especially those with due dates.

**Comment by lucbeaulieu** [comment]
Here is a proposal for a change in things3_kanban.py to add task count:
        file.write('<div class="box">' + task_link + ' (' + task_count + ')'
                   '<div class="deadline">' + deadline + '</div>' +
                   '<div class="area ' + css_class + '">' + context_link +
                   '</div>' +
                   '</div>')

where 
      task_count = str(row[THINGS3.I_COUNT]) \
            if row[THINGS3.I_COUNT] is not None else ''

Probably missing a condition that if we are looking at task, not to write this since it will always be 0...

**Comment by lucbeaulieu** [comment]
Here is a proposal to add the number of tasks to a project (if not 0) in things3_kanban.py:
       file.write('<div class="box">' + task_link + task_count +
                   '<div class="deadline">' + deadline + '</div>' +
                   '<div class="area ' + css_class + '">' + context_link +
                   '</div>' +
                   '</div>')
    file.write("</div></div>")

where:
        task_count = ' (' + str(row[THINGS3.I_COUNT]) + ')' \
            if row[THINGS3.I_COUNT] is not 0 else ' '

**Comment by lucbeaulieu** [comment]
Here is how it look like right now. The # of task within a project is displayed after the project name if it is different than 0. The nice thing with this is that you you also mix task level column, you will not get 0 for each task!

![ProjectLevel](https://user-images.githubusercontent.com/42723447/79671576-30fba900-8199-11ea-9886-e58a44ad2ade.png)
